l_name = input("What is your last name")
f_name = input("What is your first name")
message = "It is name is {}{}".format(f_name, l_name)
age = int(input("What is your age:"))
height = input("How tall are you:")
complextion = input("What is ur skin color:")
hobbies = input("What are your hobbies:")
challenge = input("what are the challenges you've ever face in life:")
determined = input("What are you determied to achive in life:")
best_friend = input("What is the name of ur best friend:")
role_model = input("Who is your role model:")
eassy = message
print(eassy)